# Generated by Django 2.0.9 on 2018-12-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(max_length=50)),
                ('papellido', models.CharField(max_length=50)),
                ('sapellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField()),
                ('nombreusuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('numerotarjeta', models.IntegerField()),
                ('banco', models.CharField(max_length=50)),
            ],
        ),
    ]
