# Generated by Django 2.0.9 on 2018-12-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20181201_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='primer_nombre',
            new_name='Primer_nombre',
        ),
    ]
